import { Project, Stakeholder, TaskNode, DependencyEdge, AuditLogEntry } from './types';

export const DEMO_PROJECT: Project = {
  id: 'proj-apex-demo',
  name: 'Apex Retail Flagship Interior Fit-Out',
  type: 'Retail Fit-Out',
  location: 'Floor 2, Apex Tower, Metro Center',
  floors: 2,
  startDate: '2026-08-01',
  targetCompletionDate: '2026-11-15',
  isDemo: true,
};

export const INITIAL_STAKEHOLDERS: Stakeholder[] = [
  {
    id: 's1',
    name: 'Sarah Lin',
    organization: 'Apex Retail Group',
    role: 'CLIENT',
    email: 'sarah@apex.com',
    avatar: 'SL',
  },
  {
    id: 's2',
    name: 'Marcus Vance',
    organization: 'Studio Forma',
    role: 'LEAD_ARCHITECT',
    email: 'marcus@forma.com',
    avatar: 'MV',
  },
  {
    id: 's3',
    name: 'David Rao',
    organization: 'Vortex Engineering',
    role: 'MEP_CONSULTANT',
    email: 'david@vortex.com',
    avatar: 'DR',
  },
  {
    id: 's4',
    name: 'Elena Rostova',
    organization: 'Prime PMO',
    role: 'PROJECT_MANAGER',
    email: 'elena@primepmo.com',
    avatar: 'ER',
  },
  {
    id: 's5',
    name: 'Frank Miller',
    organization: 'Prime Construct',
    role: 'GENERAL_CONTRACTOR',
    email: 'frank@primecon.com',
    avatar: 'FM',
  },
  {
    id: 's6',
    name: 'Tom Chen',
    organization: 'CoolAir Systems',
    role: 'HVAC_VENDOR',
    email: 'tom@coolair.com',
    avatar: 'TC',
  },
  {
    id: 's7',
    name: 'Chief Davies',
    organization: 'SafeCheck Municipal',
    role: 'FIRE_SAFETY_INSPECTOR',
    email: 'davies@safecheck.gov',
    avatar: 'CD',
  },
];

export const INITIAL_TASKS: TaskNode[] = [
  {
    id: 'T1',
    title: 'Layout Concept Freeze',
    ownerRole: 'LEAD_ARCHITECT',
    status: 'COMPLETED',
    plannedDays: 10,
    slackDays: 0,
    gridCol: 1,
    gridRow: 1,
    description: 'Spatial floorplan and mezzanine boundaries approved.',
  },
  {
    id: 'T2',
    title: 'Chiller Placement & MEP Routing',
    ownerRole: 'MEP_CONSULTANT',
    status: 'IN_PROGRESS',
    plannedDays: 7,
    slackDays: 1,
    requiresApprovalFrom: 'LEAD_ARCHITECT',
    gridCol: 2,
    gridRow: 1,
    description: 'Chiller structural load and primary riser coordinates.',
  },
  {
    id: 'T3',
    title: 'Custom Duct Fabrication',
    ownerRole: 'HVAC_VENDOR',
    status: 'NOT_STARTED',
    plannedDays: 12,
    slackDays: 0,
    gridCol: 3,
    gridRow: 1,
    description: 'Sheet metal offsite manufacturing to CAD specifications.',
  },
  {
    id: 'T4',
    title: 'Ceiling Grid & Framing',
    ownerRole: 'GENERAL_CONTRACTOR',
    status: 'NOT_STARTED',
    plannedDays: 8,
    slackDays: 2,
    gridCol: 3,
    gridRow: 2,
    description: 'Suspension framing at 3.2m false-ceiling datum.',
  },
  {
    id: 'T5',
    title: 'Fire Sprinkler Certification',
    ownerRole: 'FIRE_SAFETY_INSPECTOR',
    status: 'NOT_STARTED',
    plannedDays: 5,
    slackDays: 0,
    requiresApprovalFrom: 'FIRE_SAFETY_INSPECTOR',
    gridCol: 4,
    gridRow: 2,
    description: 'Hydraulic flow sign-off and dropper head alignment.',
  },
  {
    id: 'T6',
    title: 'Drywall Enclosure & Skim',
    ownerRole: 'GENERAL_CONTRACTOR',
    status: 'NOT_STARTED',
    plannedDays: 6,
    slackDays: 0,
    gridCol: 5,
    gridRow: 1,
    description: 'Plasterboard seal-up and acoustic insulation.',
  },
  {
    id: 'T7',
    title: 'Handover & Occupancy Permit',
    ownerRole: 'PROJECT_MANAGER',
    status: 'NOT_STARTED',
    plannedDays: 4,
    slackDays: 0,
    requiresApprovalFrom: 'CLIENT',
    gridCol: 6,
    gridRow: 1,
    description: 'Client sign-off, as-built documentation and occupation certification.',
  },
];

export const INITIAL_DEPENDENCIES: DependencyEdge[] = [
  { id: 'e1-2', source: 'T1', target: 'T2', type: 'FINISH_TO_START' },
  { id: 'e2-3', source: 'T2', target: 'T3', type: 'FINISH_TO_START' },
  { id: 'e2-4', source: 'T2', target: 'T4', type: 'FINISH_TO_START' },
  { id: 'e4-5', source: 'T4', target: 'T5', type: 'APPROVAL_GATE' },
  { id: 'e3-6', source: 'T3', target: 'T6', type: 'FINISH_TO_START' },
  { id: 'e5-6', source: 'T5', target: 'T6', type: 'FINISH_TO_START' },
  { id: 'e6-7', source: 'T6', target: 'T7', type: 'APPROVAL_GATE' },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'audit-001',
    timestamp: '09:00:00',
    actor: 'System Admin',
    role: 'SYSTEM',
    action: 'Project Baseline Initialized',
    severity: 'INFO',
    details: 'Apex Retail Flagship Interior Fit-Out baseline graph loaded successfully.',
  },
];
